package models.alert

import com.mongodb.DBObject
import com.mongodb.casbah.commons.MongoDBObject
import models.{ContextualizedStream, Contextualized, Rule}
import models.core.Observation
import org.joda.time.DateTime

/**
 * These are all messages generated by the AlertEngine to drive the
 * Incident life-cycle. Incidents are created following a DoTrigger
 * and closed once
 */
sealed abstract class AlertMsg(val rule:Rule,
                               val observations:List[Observation],
                               val created:DateTime) extends Contextualized {

  def contextualizedStream: ContextualizedStream = {
    val fields = rule.context
    val obs = observations(0)

    val context = new ContextualizedStream()

    if (fields.contains("instance")) { context.put("instance", obs.instance) }
    if (fields.contains("host")) { context.put("host", obs.host) }
    if (fields.contains("observer")) { context.put("observer", obs.observer) }
    if (fields.contains("key")) { context.put("key", obs.key) }

    context
  }
}

/**
 * Sent if a new Incident is detected to Trigger a new Incident
 * @param rule
 * @param observations
 * @param created
 */
case class DoTrigger(override val rule:Rule,
                     override val observations:List[Observation],
                     override val created:DateTime = new DateTime()) extends AlertMsg(rule, observations, created)

/**
 * Sent if new Observations are received that continue to breach the threshold
 * set by a rule. May not be used.
 * @param rule
 * @param observations
 * @param created
 */
case class DoMaintain(override val rule:Rule,
                      override val observations:List[Observation],
                      override val created:DateTime = new DateTime()) extends AlertMsg(rule, observations, created)

/**
 * Sent if new Observations are received that satisfy the clear condition set by
 * a rule. Not all rules have a clear condition.
 * @param rule
 * @param observations
 * @param created
 */
case class DoResolve(override val rule:Rule,
                     override val observations:List[Observation],
                     override val created:DateTime = new DateTime()) extends AlertMsg(rule, observations, created)

/**
 * Sent if a Rule is altered during a period of time it has a triggered alert.
 *
 * When a rule is edited while there a trigged alert for the rule, we have two options:
 *  - we can either leave the Resolve rules loaded in the AlertEngine to trigger
 *  - unload all the Resolve rules and send a DoInter message saying that while the
 *    Incident remains active, it is no longer possible that the Incident will auto-resolve
 *
 * @param rule
 * @param observations
 * @param created
 */
case class DoInter(override val rule:Rule,
                   override val observations:List[Observation],
                   override val created:DateTime = new DateTime()) extends AlertMsg(rule, observations, created)
